### ISSUE TITLE
Imageclassifier on images decided by user with createFileInput()

### ISSUE THREAD

**Issue by AndreasRef** [yining1023/teachable-machine-p5#5]
Hi

Love these examples!

I have a quick question: If I wanted to have the user interactively select an image from a folder to classify, how would you go about that? 

I can get it to run using the code snippets below integrated into [your imageclassifier-on-images example](https://github.com/yining1023/teachable-machine-p5/tree/master/imageclassifier/imageclassifier-on-images), but for some reason the prediction results are different when they are loaded by the user compared to when loaded by the program on setup, even though the images are the same. 

`
input = createFileInput(handleFile);
input.position(0, 0);
`

`
function handleFile(file) {
  print(file);
  if (file.type === 'image') {
    img = createImg(file.data);
    predictImage(img.elt, 1);
  } else {
    img = null;
  }
}
`

Have you tried to make something like this work? Or can you spot were I might be doing something wrong? Happy to send you the entire code if it helps.  

Best and thanks so much for making these examples!
Andreas

**Comment by yining1023** [comment]
Hi @AndreasRef!

Thank you so much!

I tried the code for using a file uploader input. It gave me the wrong prediction too: an image that was supposed to be class 1("anything but all black"), but it kept predicting class 2("all black").

Then I realized that maybe p5's `createImg()` function was not done with loading the image in yet, so the image we sent to predict was an empty image. I guess that's why it kept predicting the image to class 2("all black"), because the image was empty. We can fix it by adding `await` before the `createImg`, and `async` before `function handleFile(file)`:
```javascript
async function handleFile(file) {
  print(file);
  if (file.type === "image") {
    myImg = await createImg(file.data);
    predictImage(myImg.elt);
  }
}
```
I added one exmaple here: https://github.com/yining1023/teachable-machine-p5/blob/4489dd0cba2ee4ed994bdc2a3e63e35535f7f91b/imageclassifier/imageclassigier-on-images-upload/sketch.js. It can predict the right result for me:

<img width="500" alt="Screen Shot 2019-08-04 at 10 07 33 PM" src="https://user-images.githubusercontent.com/8662372/62434071-2382b980-b705-11e9-927b-909709117a16.png">

Please let me know if it works for you too. :)

**Comment by AndreasRef** [comment]
Wonderful! It works like a charm ;-). Thank you so much for the help!
